function out=cartel2dsymOptimalControl(t,depvar,par,arcid)
% returns the optimal control values for cartel2dsym
%
% this file was automatically created: 24-Aug-2024 15:01:54
% written by Dieter Grass, 2001 - 2024
	
r=par(1);
beta=par(2);
alpha=par(3);
rho=par(4);
theta=par(5);
omega=par(6);
delta=par(7);
h=par(8);
gamma1=par(9);
gamma2=par(10);
kappa=par(11);
eta=par(12);
ulow=par(13);
vlow=par(14);
w=par(15);
s=par(16);
b=par(17);
xi=par(18);
epsilon=par(19);
tau=par(20);
B=par(21);
	
switch arcid
	case 0
		out=[exp(-(-log(-gamma1./depvar(3,:)./eta./alpha)+beta.*log(depvar(1,:)+epsilon))./(-1+alpha)); ...
			exp((log(-gamma2./depvar(4,:)./eta./alpha)-beta.*log(depvar(2,:)+epsilon))./(-1+alpha)); ...
			depvar(5,:)];
	case 1
		out=[repmat(ulow,1,length(t)); ...
			exp((log(-gamma2./depvar(4,:)./eta./alpha)-beta.*log(depvar(2,:)+epsilon))./(-1+alpha)); ...
			depvar(5,:)];
	case 2
		out=[exp(-(-log(-gamma1./depvar(3,:)./eta./alpha)+beta.*log(depvar(1,:)+epsilon))./(-1+alpha)); ...
			repmat(ulow,1,length(t)); ...
			depvar(5,:)];
	case 3
		out=[exp(-(-log(-gamma1./depvar(3,:)./eta./alpha)+beta.*log(depvar(1,:)+epsilon))./(-1+alpha)); ...
			exp((log(-gamma2./depvar(4,:)./eta./alpha)-beta.*log(depvar(2,:)+epsilon))./(-1+alpha)); ...
			repmat(vlow,1,length(t))];
	case 4
		out=[depvar(5,:); ...
			depvar(6,:); ...
			B-depvar(5,:)-depvar(6,:)];
	case 5
		out=[repmat(ulow,1,length(t)); ...
			repmat(ulow,1,length(t)); ...
			depvar(5,:)];
	case 6
		out=[repmat(ulow,1,length(t)); ...
			exp((log(-gamma2./depvar(4,:)./eta./alpha)-beta.*log(depvar(2,:)+epsilon))./(-1+alpha)); ...
			repmat(vlow,1,length(t))];
	case 7
		out=[repmat(ulow,1,length(t)); ...
			depvar(5,:); ...
			B-ulow-depvar(5,:)];
	case 8
		out=[exp(-(-log(-gamma1./depvar(3,:)./eta./alpha)+beta.*log(depvar(1,:)+epsilon))./(-1+alpha)); ...
			repmat(ulow,1,length(t)); ...
			repmat(vlow,1,length(t))];
	case 9
		out=[depvar(5,:); ...
			repmat(ulow,1,length(t)); ...
			B-depvar(5,:)-ulow];
	case 10
		out=[B-depvar(5,:)-vlow; ...
			depvar(5,:); ...
			repmat(vlow,1,length(t))];
	case 11
		out=[repmat(ulow,1,length(t)); ...
			repmat(ulow,1,length(t)); ...
			repmat(vlow,1,length(t))];
	case 12
		out=[repmat(ulow,1,length(t)); ...
			repmat(ulow,1,length(t)); ...
			repmat(B,1,length(t))-2.*repmat(ulow,1,length(t))];
	case 13
		out=[repmat(ulow,1,length(t)); ...
			repmat(B,1,length(t))-repmat(ulow,1,length(t))-repmat(vlow,1,length(t)); ...
			repmat(vlow,1,length(t))];
	case 14
		out=[repmat(B,1,length(t))-repmat(ulow,1,length(t))-repmat(vlow,1,length(t)); ...
			repmat(ulow,1,length(t)); ...
			repmat(vlow,1,length(t))];
end
