function out=cartel2dsymObjectiveFunctionParameterJacobian(t,depvar,par,arcid)
% returns the canonical systems dynamics for cartel2dsym
%
% this file was automatically created: 24-Aug-2024 15:01:54
% written by Dieter Grass, 2001 - 2024
	
r=par(1);
beta=par(2);
alpha=par(3);
rho=par(4);
theta=par(5);
omega=par(6);
delta=par(7);
h=par(8);
gamma1=par(9);
gamma2=par(10);
kappa=par(11);
eta=par(12);
ulow=par(13);
vlow=par(14);
w=par(15);
s=par(16);
b=par(17);
xi=par(18);
epsilon=par(19);
tau=par(20);
B=par(21);
	
%ctrl=cartel2dsymOptimalControl(t,depvar,par,arcid);
	
switch arcid
	case 0
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-gamma2*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))-kappa*depvar(5)), ...
			 exp(-r*t)*(gamma1*log(depvar(1)+epsilon)/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))+gamma2*log(depvar(2)+epsilon)/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 exp(-r*t)*(-gamma1*(-1/alpha/(-1+alpha)+(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)^2)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-gamma2*(-1/alpha/(-1+alpha)-(log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)^2)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 exp(-r*t)*(-exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-1/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))), ...
			 exp(-r*t)*(-exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))-1/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 -exp(-r*t)*depvar(5), ...
			 exp(-r*t)*(gamma1/eta/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))+gamma2/eta/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 0, ...
			 0, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 exp(-r*t)*(gamma1*beta/(depvar(1)+epsilon)/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))+gamma2*beta/(depvar(2)+epsilon)/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 0, ...
			 0];
	
	case 1
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*ulow-gamma2*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))-kappa*depvar(5)), ...
			 exp(-r*t)*gamma2*log(depvar(2)+epsilon)/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)), ...
			 -exp(-r*t)*gamma2*(-1/alpha/(-1+alpha)-(log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)^2)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*ulow, ...
			 exp(-r*t)*(-exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))-1/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 -exp(-r*t)*depvar(5), ...
			 exp(-r*t)*gamma2/eta/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)), ...
			 -exp(-r*t)*gamma1, ...
			 0, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 exp(-r*t)*gamma2*beta/(depvar(2)+epsilon)/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)), ...
			 0, ...
			 0];
	
	case 2
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-gamma2*ulow-kappa*depvar(5)), ...
			 exp(-r*t)*gamma1*log(depvar(1)+epsilon)/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)), ...
			 -exp(-r*t)*gamma1*(-1/alpha/(-1+alpha)+(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)^2)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 exp(-r*t)*(-exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-1/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))), ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*depvar(5), ...
			 exp(-r*t)*gamma1/eta/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)), ...
			 -exp(-r*t)*gamma2, ...
			 0, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 exp(-r*t)*gamma1*beta/(depvar(1)+epsilon)/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)), ...
			 0, ...
			 0];
	
	case 3
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-gamma2*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))-kappa*vlow), ...
			 exp(-r*t)*(gamma1*log(depvar(1)+epsilon)/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))+gamma2*log(depvar(2)+epsilon)/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 exp(-r*t)*(-gamma1*(-1/alpha/(-1+alpha)+(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)^2)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-gamma2*(-1/alpha/(-1+alpha)-(log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)^2)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 exp(-r*t)*(-exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-1/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))), ...
			 exp(-r*t)*(-exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))-1/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 -exp(-r*t)*vlow, ...
			 exp(-r*t)*(gamma1/eta/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))+gamma2/eta/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 0, ...
			 -exp(-r*t)*kappa, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 exp(-r*t)*(gamma1*beta/(depvar(1)+epsilon)/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))+gamma2*beta/(depvar(2)+epsilon)/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 0, ...
			 0];
	
	case 4
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*depvar(5)-gamma2*depvar(6)-kappa*(B-depvar(5)-depvar(6))), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*depvar(5), ...
			 -exp(-r*t)*depvar(6), ...
			 exp(-r*t)*(-B+depvar(5)+depvar(6)), ...
			 0, ...
			 0, ...
			 0, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*kappa];
	
	case 5
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*ulow-gamma2*ulow-kappa*depvar(5)), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*depvar(5), ...
			 0, ...
			 exp(-r*t)*(-gamma1-gamma2), ...
			 0, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0];
	
	case 6
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*ulow-gamma2*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))-kappa*vlow), ...
			 exp(-r*t)*gamma2*log(depvar(2)+epsilon)/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)), ...
			 -exp(-r*t)*gamma2*(-1/alpha/(-1+alpha)-(log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)^2)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*ulow, ...
			 exp(-r*t)*(-exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))-1/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha))), ...
			 -exp(-r*t)*vlow, ...
			 exp(-r*t)*gamma2/eta/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)), ...
			 -exp(-r*t)*gamma1, ...
			 -exp(-r*t)*kappa, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 exp(-r*t)*gamma2*beta/(depvar(2)+epsilon)/(-1+alpha)*exp((log(-gamma2/depvar(4)/eta/alpha)-beta*log(depvar(2)+epsilon))/(-1+alpha)), ...
			 0, ...
			 0];
	
	case 7
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*ulow-gamma2*depvar(5)-kappa*(B-ulow-depvar(5))), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*depvar(5), ...
			 exp(-r*t)*(-B+ulow+depvar(5)), ...
			 0, ...
			 exp(-r*t)*(-gamma1+kappa), ...
			 0, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*kappa];
	
	case 8
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-gamma2*ulow-kappa*vlow), ...
			 exp(-r*t)*gamma1*log(depvar(1)+epsilon)/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)), ...
			 -exp(-r*t)*gamma1*(-1/alpha/(-1+alpha)+(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)^2)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 exp(-r*t)*(-exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))-1/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha))), ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*vlow, ...
			 exp(-r*t)*gamma1/eta/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)), ...
			 -exp(-r*t)*gamma2, ...
			 -exp(-r*t)*kappa, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 exp(-r*t)*gamma1*beta/(depvar(1)+epsilon)/(-1+alpha)*exp(-(-log(-gamma1/depvar(3)/eta/alpha)+beta*log(depvar(1)+epsilon))/(-1+alpha)), ...
			 0, ...
			 0];
	
	case 9
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*depvar(5)-gamma2*ulow-kappa*(B-depvar(5)-ulow)), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*depvar(5), ...
			 -exp(-r*t)*ulow, ...
			 exp(-r*t)*(-B+depvar(5)+ulow), ...
			 0, ...
			 exp(-r*t)*(-gamma2+kappa), ...
			 0, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*kappa];
	
	case 10
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*(B-depvar(5)-vlow)-gamma2*depvar(5)-kappa*vlow), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 exp(-r*t)*(-B+depvar(5)+vlow), ...
			 -exp(-r*t)*depvar(5), ...
			 -exp(-r*t)*vlow, ...
			 0, ...
			 0, ...
			 exp(-r*t)*(gamma1-kappa), ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*gamma1];
	
	case 11
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*ulow-gamma2*ulow-kappa*vlow), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*vlow, ...
			 0, ...
			 exp(-r*t)*(-gamma1-gamma2), ...
			 -exp(-r*t)*kappa, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0];
	
	case 12
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*ulow-gamma2*ulow-kappa*(B-2*ulow)), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*ulow, ...
			 exp(-r*t)*(-B+2*ulow), ...
			 0, ...
			 exp(-r*t)*(-gamma1-gamma2+2*kappa), ...
			 0, ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*kappa];
	
	case 13
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*ulow-gamma2*(B-ulow-vlow)-kappa*vlow), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 -exp(-r*t)*ulow, ...
			 exp(-r*t)*(-B+ulow+vlow), ...
			 -exp(-r*t)*vlow, ...
			 0, ...
			 exp(-r*t)*(-gamma1+gamma2), ...
			 exp(-r*t)*(gamma2-kappa), ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*gamma2];
	
	case 14
		out=[-t*exp(-r*t)*(-w*s*depvar(1)*depvar(2)-(1-w)*h*(depvar(1)+depvar(2))-gamma1*(B-ulow-vlow)-gamma2*ulow-kappa*vlow), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*(1-w)*(depvar(1)+depvar(2)), ...
			 exp(-r*t)*(-B+ulow+vlow), ...
			 -exp(-r*t)*ulow, ...
			 -exp(-r*t)*vlow, ...
			 0, ...
			 exp(-r*t)*(gamma1-gamma2), ...
			 exp(-r*t)*(gamma1-kappa), ...
			 exp(-r*t)*(-s*depvar(1)*depvar(2)+h*(depvar(1)+depvar(2))), ...
			 -exp(-r*t)*w*depvar(1)*depvar(2), ...
			 0, ...
			 0, ...
			 0, ...
			 0, ...
			 -exp(-r*t)*gamma1];
	
end
