function out=cartel2dsymDHamiltonianDU(t,depvar,par,arcid)
%
% CARTEL2DSYMDHAMILTONIANDU returns the derivative of the Lagrangefunction with respect to the implicit controls.
%
% HU=CARTEL2DSYMDHAMILTONIANDU(t,depvar,par,arcid) argument COORD returns the
% index of the implicit control.
%
% this file was automatically created: 24-Aug-2024 15:01:54
% written by Dieter Grass, 2001 - 2024
	
r=par(1);
beta=par(2);
alpha=par(3);
rho=par(4);
theta=par(5);
omega=par(6);
delta=par(7);
h=par(8);
gamma1=par(9);
gamma2=par(10);
kappa=par(11);
eta=par(12);
ulow=par(13);
vlow=par(14);
w=par(15);
s=par(16);
b=par(17);
xi=par(18);
epsilon=par(19);
tau=par(20);
B=par(21);
	
ctrl=cartel2dsymOptimalControl(t,depvar,par,arcid);
	
lagmcc=cartel2dsymLagrangeMultiplier(t,depvar,par,arcid);
	
switch arcid
	case 0
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta; ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta; ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*depvar(5,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*depvar(5,:)).*rho.*depvar(2,:)];
	
	case 1
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta+lagmcc(1,:); ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta; ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*depvar(5,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*depvar(5,:)).*rho.*depvar(2,:); ...
			ctrl(1,:)-ulow];
	
	case 2
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta; ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta+lagmcc(2,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*depvar(5,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*depvar(5,:)).*rho.*depvar(2,:); ...
			ctrl(2,:)-ulow];
	
	case 3
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta; ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta; ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)+lagmcc(3,:); ...
			ctrl(3,:)-vlow];
	
	case 4
		out=[-gamma1-depvar(3,:).*eta.*depvar(5,:).^alpha.*alpha./depvar(5,:).*(depvar(1,:)+epsilon).^beta-lagmcc(4,:); ...
			-gamma2-depvar(4,:).*eta.*depvar(6,:).^alpha.*alpha./depvar(6,:).*(depvar(2,:)+epsilon).^beta-lagmcc(4,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)-lagmcc(4,:); ...
			B-depvar(5,:)-depvar(6,:)-ctrl(3,:)];
	
	case 5
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta+lagmcc(1,:); ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta+lagmcc(2,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*depvar(5,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*depvar(5,:)).*rho.*depvar(2,:); ...
			ctrl(1,:)-ulow; ...
			ctrl(2,:)-ulow];
	
	case 6
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta+lagmcc(1,:); ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta; ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)+lagmcc(3,:); ...
			ctrl(1,:)-ulow; ...
			ctrl(3,:)-vlow];
	
	case 7
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta+lagmcc(1,:)-lagmcc(4,:); ...
			-gamma2-depvar(4,:).*eta.*depvar(5,:).^alpha.*alpha./depvar(5,:).*(depvar(2,:)+epsilon).^beta-lagmcc(4,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)-lagmcc(4,:); ...
			ctrl(1,:)-ulow; ...
			B-ctrl(1,:)-depvar(5,:)-ctrl(3,:)];
	
	case 8
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta; ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta+lagmcc(2,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)+lagmcc(3,:); ...
			ctrl(2,:)-ulow; ...
			ctrl(3,:)-vlow];
	
	case 9
		out=[-gamma1-depvar(3,:).*eta.*depvar(5,:).^alpha.*alpha./depvar(5,:).*(depvar(1,:)+epsilon).^beta-lagmcc(4,:); ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta+lagmcc(2,:)-lagmcc(4,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)-lagmcc(4,:); ...
			ctrl(2,:)-ulow; ...
			B-depvar(5,:)-ctrl(2,:)-ctrl(3,:)];
	
	case 10
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta-lagmcc(4,:); ...
			-gamma2-depvar(4,:).*eta.*depvar(5,:).^alpha.*alpha./depvar(5,:).*(depvar(2,:)+epsilon).^beta-lagmcc(4,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)+lagmcc(3,:)-lagmcc(4,:); ...
			ctrl(3,:)-vlow; ...
			B-ctrl(1,:)-depvar(5,:)-ctrl(3,:)];
	
	case 11
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta+lagmcc(1,:); ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta+lagmcc(2,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)+lagmcc(3,:); ...
			ctrl(1,:)-ulow; ...
			ctrl(2,:)-ulow; ...
			ctrl(3,:)-vlow];
	
	case 12
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta+lagmcc(1,:)-lagmcc(4,:); ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta+lagmcc(2,:)-lagmcc(4,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)-lagmcc(4,:); ...
			ctrl(1,:)-ulow; ...
			ctrl(2,:)-ulow; ...
			B-ctrl(1,:)-ctrl(2,:)-ctrl(3,:)];
	
	case 13
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta+lagmcc(1,:)-lagmcc(4,:); ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta-lagmcc(4,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)+lagmcc(3,:)-lagmcc(4,:); ...
			ctrl(1,:)-ulow; ...
			ctrl(3,:)-vlow; ...
			B-ctrl(1,:)-ctrl(2,:)-ctrl(3,:)];
	
	case 14
		out=[-gamma1-depvar(3,:).*eta.*ctrl(1,:).^alpha.*alpha./ctrl(1,:).*(depvar(1,:)+epsilon).^beta-lagmcc(4,:); ...
			-gamma2-depvar(4,:).*eta.*ctrl(2,:).^alpha.*alpha./ctrl(2,:).*(depvar(2,:)+epsilon).^beta+lagmcc(2,:)-lagmcc(4,:); ...
			-kappa-depvar(3,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(1,:)-depvar(4,:).*(delta-b).*xi.*exp(-xi.*ctrl(3,:)).*rho.*depvar(2,:)+lagmcc(3,:)-lagmcc(4,:); ...
			ctrl(2,:)-ulow; ...
			ctrl(3,:)-vlow; ...
			B-ctrl(1,:)-ctrl(2,:)-ctrl(3,:)];
	
end
