function out=cartel2dsymSymbolicEquilibriumEquation(arcid)
% equations for an equilibrium of the canonical system
%
% this file was automatically created: 24-Aug-2024 15:01:54
% written by Dieter Grass, 2001 - 2024
	
switch arcid
	case 0
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*v))*rho*C1-eta*exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha))^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*v))*rho*C2-eta*exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha))^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*v))*rho-eta*exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha))^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*v))*rho-eta*exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha))^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 1
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*v))*rho*C1-eta*ulow^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*v))*rho*C2-eta*exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha))^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*v))*rho-eta*ulow^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*v))*rho-eta*exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha))^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 2
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*v))*rho*C1-eta*exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha))^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*v))*rho*C2-eta*ulow^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*v))*rho-eta*exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha))^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*v))*rho-eta*ulow^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 3
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*vlow))*rho*C1-eta*exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha))^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*vlow))*rho*C2-eta*exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha))^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*vlow))*rho-eta*exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha))^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*vlow))*rho-eta*exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha))^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 4
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*(B-u1-u2)))*rho*C1-eta*u1^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*(B-u1-u2)))*rho*C2-eta*u2^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*(B-u1-u2)))*rho-eta*u1^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*(B-u1-u2)))*rho-eta*u2^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 5
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*v))*rho*C1-eta*ulow^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*v))*rho*C2-eta*ulow^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*v))*rho-eta*ulow^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*v))*rho-eta*ulow^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 6
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*vlow))*rho*C1-eta*ulow^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*vlow))*rho*C2-eta*exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha))^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*vlow))*rho-eta*ulow^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*vlow))*rho-eta*exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha))^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 7
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*(B-ulow-u2)))*rho*C1-eta*ulow^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*(B-ulow-u2)))*rho*C2-eta*u2^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*(B-ulow-u2)))*rho-eta*ulow^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*(B-ulow-u2)))*rho-eta*u2^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 8
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*vlow))*rho*C1-eta*exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha))^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*vlow))*rho*C2-eta*ulow^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*vlow))*rho-eta*exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha))^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*vlow))*rho-eta*ulow^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 9
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*(B-u1-ulow)))*rho*C1-eta*u1^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*(B-u1-ulow)))*rho*C2-eta*ulow^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*(B-u1-ulow)))*rho-eta*u1^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*(B-u1-ulow)))*rho-eta*ulow^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 10
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*vlow))*rho*C1-eta*(B-u2-vlow)^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*vlow))*rho*C2-eta*u2^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*vlow))*rho-eta*(B-u2-vlow)^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*vlow))*rho-eta*u2^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 11
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*vlow))*rho*C1-eta*ulow^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*vlow))*rho*C2-eta*ulow^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*vlow))*rho-eta*ulow^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*vlow))*rho-eta*ulow^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 12
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*(B-2*ulow)))*rho*C1-eta*ulow^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*(B-2*ulow)))*rho*C2-eta*ulow^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*(B-2*ulow)))*rho-eta*ulow^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*(B-2*ulow)))*rho-eta*ulow^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 13
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*vlow))*rho*C1-eta*ulow^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*vlow))*rho*C2-eta*(B-ulow-vlow)^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*vlow))*rho-eta*ulow^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*vlow))*rho-eta*(B-ulow-vlow)^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
	case 14
		out=mystr2sym(['[tau+(b+(delta-b)*exp(-xi*vlow))*rho*C1-eta*(B-ulow-vlow)^alpha*(C1+epsilon)^beta-theta*C1*C2-omega*C1^2,' ...
			'tau+(b+(delta-b)*exp(-xi*vlow))*rho*C2-eta*ulow^alpha*(C2+epsilon)^beta-theta*C1*C2-omega*C2^2,' ...
			'r*lambda1+w*s*C2+(1-w)*h-lambda1*((b+(delta-b)*exp(-xi*vlow))*rho-eta*(B-ulow-vlow)^alpha*(C1+epsilon)^beta*beta/(C1+epsilon)-theta*C2-2*omega*C1)+lambda2*theta*C2,' ...
			'r*lambda2+w*s*C1+(1-w)*h+lambda1*theta*C1-lambda2*((b+(delta-b)*exp(-xi*vlow))*rho-eta*ulow^alpha*(C2+epsilon)^beta*beta/(C2+epsilon)-theta*C1-2*omega*C2)]']);
	
end
