function out=cartel2dsymSymbolicOptimalControl(arcid)
% returns the symbolic expression of the optimal control value
%
% this file was automatically created: 24-Aug-2024 15:01:54
% written by Dieter Grass, 2001 - 2024
	
switch arcid
	case 0	
		out=mystr2sym(['[exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha)),' ...
			'exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha)),' ...
			'v]']);
	case 1	
		out=mystr2sym(['[ulow,' ...
			'exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha)),' ...
			'v]']);
	case 2	
		out=mystr2sym(['[exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha)),' ...
			'ulow,' ...
			'v]']);
	case 3	
		out=mystr2sym(['[exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha)),' ...
			'exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha)),' ...
			'vlow]']);
	case 4	
		out=mystr2sym(['[u1,' ...
			'u2,' ...
			'B-u1-u2]']);
	case 5	
		out=mystr2sym(['[ulow,' ...
			'ulow,' ...
			'v]']);
	case 6	
		out=mystr2sym(['[ulow,' ...
			'exp((log(-gamma2/lambda2/eta/alpha)-beta*log(C2+epsilon))/(-1+alpha)),' ...
			'vlow]']);
	case 7	
		out=mystr2sym(['[ulow,' ...
			'u2,' ...
			'B-ulow-u2]']);
	case 8	
		out=mystr2sym(['[exp(-(-log(-gamma1/lambda1/eta/alpha)+beta*log(C1+epsilon))/(-1+alpha)),' ...
			'ulow,' ...
			'vlow]']);
	case 9	
		out=mystr2sym(['[u1,' ...
			'ulow,' ...
			'B-u1-ulow]']);
	case 10	
		out=mystr2sym(['[B-u2-vlow,' ...
			'u2,' ...
			'vlow]']);
	case 11	
		out=mystr2sym(['[ulow,' ...
			'ulow,' ...
			'vlow]']);
	case 12	
		out=mystr2sym(['[ulow,' ...
			'ulow,' ...
			'B-2*ulow]']);
	case 13	
		out=mystr2sym(['[ulow,' ...
			'B-ulow-vlow,' ...
			'vlow]']);
	case 14	
		out=mystr2sym(['[B-ulow-vlow,' ...
			'ulow,' ...
			'vlow]']);
end
