function [out,coord]=cartel2dsymD2LagrangianDUDP(t,depvar,par,arcid)
%
% CARTEL2DSYMD2LAGRANGIANDUDP returns the second order derivative of the Lagrangefunction with respect
% to the implicit controls and parameter name.
%
% LUP=CARTEL2DSYMD2LAGRANGIANDUDP(t,depvar,par,arcid) let m=#implicit controls,
% k=#parameter and n=#time grid, then LUP is of size m*k x n.
%
% [LUP,COORD]=CARTEL2DSYMD2LAGRANGIANDUDP(t,depvar,par,arcid) argument COORD returns the
% index of the implicit control.
%
% this file was automatically created: 24-Aug-2024 15:01:54
% written by Dieter Grass, 2001 - 2024
	
r=par(1);
beta=par(2);
alpha=par(3);
rho=par(4);
theta=par(5);
omega=par(6);
delta=par(7);
h=par(8);
gamma1=par(9);
gamma2=par(10);
kappa=par(11);
eta=par(12);
ulow=par(13);
vlow=par(14);
w=par(15);
s=par(16);
b=par(17);
xi=par(18);
epsilon=par(19);
tau=par(20);
B=par(21);
	
switch arcid
	case 0
		out=[repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*(delta-b)*xi*exp(-xi*depvar(5,:))*depvar(1,:)-depvar(4,:)*(delta-b)*xi*exp(-xi*depvar(5,:))*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(1,:)-depvar(4,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			depvar(3,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(1,:)+depvar(4,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			-depvar(3,:)*(delta-b)*exp(-xi*depvar(5,:))*rho*depvar(1,:)+depvar(3,:)*(delta-b)*xi*depvar(5,:)*exp(-xi*depvar(5,:))*rho*depvar(1,:)-depvar(4,:)*(delta-b)*exp(-xi*depvar(5,:))*rho*depvar(2,:)+depvar(4,:)*(delta-b)*xi*depvar(5,:)*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t))];
		coord=3;
	
	case 1
		out=[repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*(delta-b)*xi*exp(-xi*depvar(5,:))*depvar(1,:)-depvar(4,:)*(delta-b)*xi*exp(-xi*depvar(5,:))*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(1,:)-depvar(4,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			depvar(3,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(1,:)+depvar(4,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			-depvar(3,:)*(delta-b)*exp(-xi*depvar(5,:))*rho*depvar(1,:)+depvar(3,:)*(delta-b)*xi*depvar(5,:)*exp(-xi*depvar(5,:))*rho*depvar(1,:)-depvar(4,:)*(delta-b)*exp(-xi*depvar(5,:))*rho*depvar(2,:)+depvar(4,:)*(delta-b)*xi*depvar(5,:)*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t))];
		coord=3;
	
	case 2
		out=[repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*(delta-b)*xi*exp(-xi*depvar(5,:))*depvar(1,:)-depvar(4,:)*(delta-b)*xi*exp(-xi*depvar(5,:))*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(1,:)-depvar(4,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			depvar(3,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(1,:)+depvar(4,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			-depvar(3,:)*(delta-b)*exp(-xi*depvar(5,:))*rho*depvar(1,:)+depvar(3,:)*(delta-b)*xi*depvar(5,:)*exp(-xi*depvar(5,:))*rho*depvar(1,:)-depvar(4,:)*(delta-b)*exp(-xi*depvar(5,:))*rho*depvar(2,:)+depvar(4,:)*(delta-b)*xi*depvar(5,:)*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t))];
		coord=3;
	
	case 3
		out=[];
		coord=[];
	
	case 4
		out=[repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*eta*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta*log(depvar(1,:)+epsilon); ...
			-depvar(4,:)*eta*depvar(6,:)^alpha*alpha/depvar(6,:)*(depvar(2,:)+epsilon)^beta*log(depvar(2,:)+epsilon); ...
			-depvar(3,:)*eta*depvar(5,:)^alpha*log(depvar(5,:))*alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta-depvar(3,:)*eta*depvar(5,:)^alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta; ...
			-depvar(4,:)*eta*depvar(6,:)^alpha*log(depvar(6,:))*alpha/depvar(6,:)*(depvar(2,:)+epsilon)^beta-depvar(4,:)*eta*depvar(6,:)^alpha/depvar(6,:)*(depvar(2,:)+epsilon)^beta; ...
			depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*depvar(1,:)*delta-depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*depvar(1,:)*b+depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*depvar(2,:)*delta-depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*depvar(2,:)*b; ...
			depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*depvar(1,:)*delta-depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*depvar(1,:)*b+depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*depvar(2,:)*delta-depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*depvar(2,:)*b; ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)+depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:); ...
			depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)+depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(1,1,length(t)); ...
			repmat(1,1,length(t)); ...
			-depvar(3,:)*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta; ...
			-depvar(4,:)*depvar(6,:)^alpha*alpha/depvar(6,:)*(depvar(2,:)+epsilon)^beta; ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)-depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:); ...
			-depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)-depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:); ...
			depvar(3,:)*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*delta+depvar(3,:)*xi*(-B+depvar(5,:)+depvar(6,:))*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*delta-depvar(3,:)*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*b-depvar(3,:)*xi*(-B+depvar(5,:)+depvar(6,:))*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*b+depvar(4,:)*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*delta+depvar(4,:)*xi*(-B+depvar(5,:)+depvar(6,:))*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*delta-depvar(4,:)*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*b-depvar(4,:)*xi*(-B+depvar(5,:)+depvar(6,:))*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*b; ...
			depvar(3,:)*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*delta+depvar(3,:)*xi*(-B+depvar(5,:)+depvar(6,:))*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*delta-depvar(3,:)*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*b-depvar(3,:)*xi*(-B+depvar(5,:)+depvar(6,:))*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*b+depvar(4,:)*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*delta+depvar(4,:)*xi*(-B+depvar(5,:)+depvar(6,:))*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*delta-depvar(4,:)*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*b-depvar(4,:)*xi*(-B+depvar(5,:)+depvar(6,:))*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*b; ...
			-depvar(3,:)*eta*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta*beta/(depvar(1,:)+epsilon); ...
			-depvar(4,:)*eta*depvar(6,:)^alpha*alpha/depvar(6,:)*(depvar(2,:)+epsilon)^beta*beta/(depvar(2,:)+epsilon); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi^2*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*delta+depvar(3,:)*xi^2*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*b-depvar(4,:)*xi^2*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*delta+depvar(4,:)*xi^2*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*b; ...
			-depvar(3,:)*xi^2*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*delta+depvar(3,:)*xi^2*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(1,:)*b-depvar(4,:)*xi^2*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*delta+depvar(4,:)*xi^2*exp(-xi*(B-depvar(5,:)-depvar(6,:)))*rho*depvar(2,:)*b];
		coord=[1,2];
	
	case 5
		out=[repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*(delta-b)*xi*exp(-xi*depvar(5,:))*depvar(1,:)-depvar(4,:)*(delta-b)*xi*exp(-xi*depvar(5,:))*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(1,:)-depvar(4,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			depvar(3,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(1,:)+depvar(4,:)*xi*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			-depvar(3,:)*(delta-b)*exp(-xi*depvar(5,:))*rho*depvar(1,:)+depvar(3,:)*(delta-b)*xi*depvar(5,:)*exp(-xi*depvar(5,:))*rho*depvar(1,:)-depvar(4,:)*(delta-b)*exp(-xi*depvar(5,:))*rho*depvar(2,:)+depvar(4,:)*(delta-b)*xi*depvar(5,:)*exp(-xi*depvar(5,:))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t))];
		coord=3;
	
	case 6
		out=[];
		coord=[];
	
	case 7
		out=[repmat(0,1,length(t)); ...
			-depvar(4,:)*eta*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta*log(depvar(2,:)+epsilon); ...
			-depvar(4,:)*eta*depvar(5,:)^alpha*log(depvar(5,:))*alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta-depvar(4,:)*eta*depvar(5,:)^alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta; ...
			depvar(3,:)*xi*exp(-xi*(B-ulow-depvar(5,:)))*depvar(1,:)*delta-depvar(3,:)*xi*exp(-xi*(B-ulow-depvar(5,:)))*depvar(1,:)*b+depvar(4,:)*xi*exp(-xi*(B-ulow-depvar(5,:)))*depvar(2,:)*delta-depvar(4,:)*xi*exp(-xi*(B-ulow-depvar(5,:)))*depvar(2,:)*b; ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			depvar(3,:)*xi*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)+depvar(4,:)*xi*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(1,1,length(t)); ...
			-depvar(4,:)*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta; ...
			depvar(3,:)*xi^2*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)*delta-depvar(3,:)*xi^2*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)*b+depvar(4,:)*xi^2*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:)*delta-depvar(4,:)*xi^2*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:)*b; ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)-depvar(4,:)*xi*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:); ...
			depvar(3,:)*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)*delta+depvar(3,:)*xi*(-B+ulow+depvar(5,:))*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)*delta-depvar(3,:)*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)*b-depvar(3,:)*xi*(-B+ulow+depvar(5,:))*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)*b+depvar(4,:)*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:)*delta+depvar(4,:)*xi*(-B+ulow+depvar(5,:))*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:)*delta-depvar(4,:)*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:)*b-depvar(4,:)*xi*(-B+ulow+depvar(5,:))*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:)*b; ...
			-depvar(4,:)*eta*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta*beta/(depvar(2,:)+epsilon); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi^2*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)*delta+depvar(3,:)*xi^2*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(1,:)*b-depvar(4,:)*xi^2*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:)*delta+depvar(4,:)*xi^2*exp(-xi*(B-ulow-depvar(5,:)))*rho*depvar(2,:)*b];
		coord=2;
	
	case 8
		out=[];
		coord=[];
	
	case 9
		out=[repmat(0,1,length(t)); ...
			-depvar(3,:)*eta*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta*log(depvar(1,:)+epsilon); ...
			-depvar(3,:)*eta*depvar(5,:)^alpha*log(depvar(5,:))*alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta-depvar(3,:)*eta*depvar(5,:)^alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta; ...
			depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-ulow))*depvar(1,:)*delta-depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-ulow))*depvar(1,:)*b+depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-ulow))*depvar(2,:)*delta-depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-ulow))*depvar(2,:)*b; ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)+depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:); ...
			repmat(0,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(1,1,length(t)); ...
			-depvar(3,:)*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta; ...
			depvar(3,:)*xi^2*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)*delta-depvar(3,:)*xi^2*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)*b+depvar(4,:)*xi^2*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:)*delta-depvar(4,:)*xi^2*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:)*b; ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)-depvar(4,:)*xi*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:); ...
			depvar(3,:)*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)*delta+depvar(3,:)*xi*(-B+depvar(5,:)+ulow)*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)*delta-depvar(3,:)*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)*b-depvar(3,:)*xi*(-B+depvar(5,:)+ulow)*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)*b+depvar(4,:)*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:)*delta+depvar(4,:)*xi*(-B+depvar(5,:)+ulow)*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:)*delta-depvar(4,:)*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:)*b-depvar(4,:)*xi*(-B+depvar(5,:)+ulow)*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:)*b; ...
			-depvar(3,:)*eta*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(1,:)+epsilon)^beta*beta/(depvar(1,:)+epsilon); ...
			repmat(0,1,length(t)); ...
			-depvar(3,:)*xi^2*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)*delta+depvar(3,:)*xi^2*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(1,:)*b-depvar(4,:)*xi^2*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:)*delta+depvar(4,:)*xi^2*exp(-xi*(B-depvar(5,:)-ulow))*rho*depvar(2,:)*b];
		coord=1;
	
	case 10
		out=[repmat(0,1,length(t)); ...
			-depvar(4,:)*eta*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta*log(depvar(2,:)+epsilon)+depvar(3,:)*eta*(B-depvar(5,:)-vlow)^alpha*alpha*(depvar(1,:)+epsilon)^beta*log(depvar(1,:)+epsilon)/(B-depvar(5,:)-vlow); ...
			-depvar(4,:)*eta*depvar(5,:)^alpha*log(depvar(5,:))*alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta-depvar(4,:)*eta*depvar(5,:)^alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta+(depvar(3,:)*eta*(B-depvar(5,:)-vlow)^alpha*log(B-depvar(5,:)-vlow)*alpha*(depvar(1,:)+epsilon)^beta+depvar(3,:)*eta*(B-depvar(5,:)-vlow)^alpha*(depvar(1,:)+epsilon)^beta)/(B-depvar(5,:)-vlow); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(1,1,length(t)); ...
			repmat(-1,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(4,:)*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta+depvar(3,:)*(B-depvar(5,:)-vlow)^alpha*alpha*(depvar(1,:)+epsilon)^beta/(B-depvar(5,:)-vlow); ...
			repmat(0,1,length(t)); ...
			(-gamma1-depvar(3,:)*eta*(B-depvar(5,:)-vlow)^alpha*alpha^2/(B-depvar(5,:)-vlow)*(depvar(1,:)+epsilon)^beta)/(B-depvar(5,:)-vlow)+(gamma1*B-gamma1*depvar(5,:)-gamma1*vlow+depvar(3,:)*eta*(B-depvar(5,:)-vlow)^alpha*alpha*(depvar(1,:)+epsilon)^beta)/(B-depvar(5,:)-vlow)^2; ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			repmat(0,1,length(t)); ...
			-depvar(4,:)*eta*depvar(5,:)^alpha*alpha/depvar(5,:)*(depvar(2,:)+epsilon)^beta*beta/(depvar(2,:)+epsilon)+depvar(3,:)*eta*(B-depvar(5,:)-vlow)^alpha*alpha*(depvar(1,:)+epsilon)^beta*beta/(depvar(1,:)+epsilon)/(B-depvar(5,:)-vlow); ...
			repmat(0,1,length(t)); ...
			(gamma1+depvar(3,:)*eta*(B-depvar(5,:)-vlow)^alpha*alpha^2/(B-depvar(5,:)-vlow)*(depvar(1,:)+epsilon)^beta)/(B-depvar(5,:)-vlow)-(gamma1*B-gamma1*depvar(5,:)-gamma1*vlow+depvar(3,:)*eta*(B-depvar(5,:)-vlow)^alpha*alpha*(depvar(1,:)+epsilon)^beta)/(B-depvar(5,:)-vlow)^2];
		coord=2;
	
	case 11
		out=[];
		coord=[];
	
	case 12
		out=[];
		coord=[];
	
	case 13
		out=[];
		coord=[];
	
	case 14
		out=[];
		coord=[];
	
end
