function epMF = endpointmanifold(ocObj,idx,varargin)
%
% ENDPOINTMANIFOLD returns the endpoint manifold(s) stored in OCOBJ
%
% SLMF=ENDPOINTMANIFOLD(OCOBJ) returns a cell arry of slice manifold(s)
% stored in the 'Result' field 'EndPointManifold' of OCOBJ. If this field
% does not exist it is generated by the end points of
% 'ContinuationSolution'. 

% variable declaration
epMF{1}=occurve();

contResultStruct=contresult(ocObj,[],varargin{:});

if isempty(ocObj) || isempty(contResultStruct)
    return
end

if nargin==1 || isempty(idx)
    idx=1:numel(contResultStruct);
end
try
    % if field SliceManifold exists
    epMF=cellfun(@getfield,contResultStruct(idx),repmat({'EndpointManifold'},1,numel(idx)),'UniformOutput',false);
catch
    % otherwise generate from initial points of ContinuationSolution
    for ii=1:numel(idx)
        pt=[];
        pt.arcposition=[];
        if ~isfield(contResultStruct{idx(ii)},'ContinuationSolution');
            ocmatmsg('Neither field ''EndpointManifold'' nor ''ContinuationSolution'' exist.')
            %return
        end
        for jj=1:numel(contResultStruct{idx(ii)}.ContinuationSolution)
            pt.y(:,jj)=contResultStruct{idx(ii)}.ContinuationSolution(jj).y(:,end);
        end
        pt.arcarg=contResultStruct{idx(ii)}.ContinuationSolution(jj).arcarg(ones(1,jj));
        pt.modelname=contResultStruct{idx(ii)}.ContinuationSolution(jj).modelname;
        epMF{ii}=occurve(pt);
    end
end