function [idx,tag,objh] = getpoint(varargin)
%
% GETPOINT reads out the point of a solution object.
%
% GETPOINT mainly bases on the MATLAB function GINPUT.

idx=[];
tag=[];
how_many = [];

if nargin
    how_many=varargin{1};
end
objh=zeros(how_many,1);
if isempty(how_many)
    how_many=1;
end

fig = gcf;
figure(fig);

% Remove figure button functions
state = uisuspend(fig);
%pointer = get(gcf,'pointer');
set(gcf,'pointer','arrow');

% We need to pump the event queue on unix
% before calling WAITFORBUTTONPRESS
fprintf('Choose ''%d'' line objects with the mouse in the current axes.',how_many)
drawnow


while how_many ~= 0
    % Use no-side effect WAITFORBUTTONPRESS
    waserr = 0;
    try
        keydown = wfbp;
    catch
        waserr = 1;
    end
    if(waserr == 1)
        if(ishandle(fig))
            set(fig,'units',fig_units);
            uirestore(state);
            error('Interrupted');
        else
            error('Interrupted by figure deletion');
        end
    end

    ptr_fig = get(0,'CurrentFigure');

    if(ptr_fig == fig)
        if keydown
            scrn_pt = get(0, 'PointerLocation');
            set(fig,'units','pixels')
            loc = get(fig, 'Position');
            % We need to compensate for an off-by-one error:
            pt = [scrn_pt(1) - loc(1) + 1, scrn_pt(2) - loc(2) + 1];
            set(fig,'CurrentPoint',pt);
        end
        pt = get(gca, 'CurrentPoint');
        pt=pt(1,1:2).';
        if strcmp(get(gco,'Type'),'line')
            tag{end+1} = get(gco, 'Tag');
            data=[get(gco,'XData');get(gco,'YData')];
            [dum,tmp]=min(sum(abs(data-pt(:,ones(1,size(data,2))))));
            idx(end+1)=tmp;
        end
        how_many = how_many - 1;
        objh(end-how_many)=gco;
    end

    uirestore(state);
end
tag=char(tag);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function key = wfbp
%WFBP   Replacement for WAITFORBUTTONPRESS that has no side effects.

fig = gcf;
current_char = [];

% Now wait for that buttonpress, and check for error conditions
waserr = 0;
try
    h=findall(fig,'type','uimenu','accel','C');   % Disabling ^C for edit menu so the only ^C is for
    set(h,'accel','');                            % interrupting the function.
    keydown = waitforbuttonpress;
    current_char = double(get(fig,'CurrentCharacter')); % Capturing the character.
    if~isempty(current_char) & (keydown == 1)           % If the character was generated by the
        if(current_char == 3)                       % current keypress AND is ^C, set 'waserr'to 1
            waserr = 1;                             % so that it errors out.
        end
    end

    set(h,'accel','C');                                 % Set back the accelerator for edit menu.
catch
    waserr = 1;
end
drawnow;
if(waserr == 1)
    set(h,'accel','C');                                % Set back the accelerator if it errored out.
    error('Interrupted');
end

if nargout>0, key = keydown; end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
