function [tag,objh] = gettag(varargin)
%
% GETTAG reads out the tags of lineseries graphics objects.
%
% OUT = GETTAG(N) reads out the 'TAG' property of N lineseries graphics
% objects. The lineseries graphics objects are marked using the mouse. If
% the lines are plotted with one of the OCMAT stdocmodel plotting commands
% (plotcont, plotlimitset, ...) the TAGs are unique names. The TAGs are
% returned in the cell array OUT.    
%
% GETTAG mainly bases on the MATLAB function GINPUT.

tag=[];
how_many = [];

if nargin
    how_many=varargin{1};
end
objh=zeros(how_many,1);
if isempty(how_many)
    how_many=1;
end

fig = gcf;
figure(fig);

% Remove figure button functions
state = uisuspend(fig);
%pointer = get(gcf,'pointer');
set(gcf,'pointer','arrow');

% We need to pump the event queue on unix
% before calling WAITFORBUTTONPRESS
fprintf('Choose ''%d'' line objects with the mouse in the current axes.',how_many)
drawnow


while how_many ~= 0
    % Use no-side effect WAITFORBUTTONPRESS
    waserr = 0;
    try
        keydown = wfbp;
    catch
        waserr = 1;
    end
    if(waserr == 1)
        if(ishandle(fig))
            set(fig,'units',fig_units);
            uirestore(state);
            error('Interrupted');
        else
            error('Interrupted by figure deletion');
        end
    end

    ptr_fig = get(0,'CurrentFigure');

    if(ptr_fig == fig)
        tag{end+1} = get(gco, 'Tag');
        how_many = how_many - 1;
        objh(end-how_many)=gco;
    end

    uirestore(state);
end
tag=char(tag);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function key = wfbp
%WFBP   Replacement for WAITFORBUTTONPRESS that has no side effects.

fig = gcf;
current_char = [];

% Now wait for that buttonpress, and check for error conditions
waserr = 0;
try
    h=findall(fig,'type','uimenu','accel','C');   % Disabling ^C for edit menu so the only ^C is for
    set(h,'accel','');                            % interrupting the function.
    keydown = waitforbuttonpress;
    current_char = double(get(fig,'CurrentCharacter')); % Capturing the character.
    if~isempty(current_char) & (keydown == 1)           % If the character was generated by the
        if(current_char == 3)                       % current keypress AND is ^C, set 'waserr'to 1
            waserr = 1;                             % so that it errors out.
        end
    end

    set(h,'accel','C');                                 % Set back the accelerator for edit menu.
catch
    waserr = 1;
end
drawnow;
if(waserr == 1)
    set(h,'accel','C');                                % Set back the accelerator if it errored out.
    error('Interrupted');
end

if nargout>0, key = keydown; end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
